package luminia.backend.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.*;

@Entity(name = "User")
@Table(name = "users")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class User {
    @Id
    @Column(name = "id", nullable = false)
    private Long id; // Generated by SSO
    private double rating;
    private String username;
    @Column(name = "full_name")
    private String fullName;
    // Integrations
    private Long discordId;
    @Column(name = "social_username")
    private String socialUsername;
    // Privacy Settings
    @Column(name = "is_name_protected")
    private boolean nameProtected;
    @Column(name = "is_social_protected")
    private boolean socialProtected;
}
